diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

model_params:
#  im_channels : 1
  im_channels : 3
#  im_size : 28
  im_size : 32
#  down_channels : [32, 64, 128, 256]
  down_channels : [64, 128, 256, 512]
#  mid_channels : [256, 256, 128]
  mid_channels : [512, 512, 256]
  down_sample : [True, True, False]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4

train_params:
  noise_scheduler: 'linear' # 'cosine'
  task_name: 'default'
  batch_size: 128 #training in 3090
  num_epochs: 500
  num_samples : 5 #sampling in 2060
  num_grid_rows : 10
  lr: 0.0001
  ckpt_name: 'ddpm_ckpt.pth'
